[project]
name = "ticket-sales-platform-api"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.19.1",
    "bcrypt>=5.0.0",
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "psycopg[binary]>=3.3.4",
    "pydantic-settings>=2.15.0",
    "pyjwt>=2.13.0",
    "sqlalchemy>=2.0.52",
    "uvicorn[standard]>=0.52.1",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.2",
]

[tool.ruff.lint]
ignore = ["B008"]
